# Generated by Django 4.2.2 on 2024-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailsendattempt",
            options={
                "ordering": ["-last_attempt_time"],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытка рассылок",
            },
        ),
    ]
