# Generated by Django 4.2.2 on 2024-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0003_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активна"),
        ),
    ]
