# Generated by Django 4.2.2 on 2024-11-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0004_newsletter_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время отправки следующей рассылки",
            ),
        ),
    ]
