# Generated by Django 4.2.2 on 2024-11-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0005_alter_newsletter_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="period",
            field=models.CharField(
                choices=[
                    ("days", "Ежедневная рассылка"),
                    ("weeks", "Еженедельная рассылка"),
                    ("months", "Ежемесячная рассылка"),
                ],
                max_length=10,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
