# Generated by Django 4.2.2 on 2024-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0006_alter_newsletter_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_date",
            field=models.DateTimeField(
                verbose_name="Дата и время отправки следующей рассылки"
            ),
        ),
    ]
