# Generated by Django 4.2.2 on 2024-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0007_alter_newsletter_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время отправки следующей рассылки",
            ),
        ),
    ]
