# Generated by Django 4.2.2 on 2024-11-22 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailmaster", "0011_alter_newsletter_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailmaster.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="period",
            field=models.CharField(
                choices=[
                    ("days", "Ежедневная рассылка"),
                    ("weeks", "Еженедельная рассылка"),
                    ("months", "Ежемесячная рассылка"),
                ],
                max_length=10,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_date",
            field=models.DateTimeField(verbose_name="Дата начала рассылки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("active", "Запущена"),
                    ("closed", "Завершена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
    ]
