# Generated by Django 4.2.2 on 2025-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0013_newsletter_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, verbose_name="комментарий"),
        ),
        migrations.AlterField(
            model_name="emailsendattempt",
            name="response",
            field=models.TextField(blank=True, verbose_name="ответ почтового сервера"),
        ),
    ]
