# Generated by Django 4.2.2 on 2025-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0016_alter_newsletter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="sent_today",
            field=models.BooleanField(default=False),
        ),
    ]
