# Generated by Django 4.2.2 on 2025-02-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0017_newsletter_sent_today"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="clients",
            field=models.ManyToManyField(
                related_name="newsletters",
                to="mailmaster.client",
                verbose_name="Клиенты",
            ),
        ),
    ]
