# Generated by Django 4.2.2 on 2025-02-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0021_remove_newsletter_user_newsletter_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("email",),
                "permissions": [("can_view_by_manager", "Право менеджера на просмотр")],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("title",),
                "permissions": [("can_view_by_manager", "Право менеджера на просмотр")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_by_manager", "Право менеджера на просмотр"),
                    ("can_change_by_manager", "Право менеджера на редактирование"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
