# Generated by Django 4.2.2 on 2025-02-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0023_alter_client_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("title",),
                "permissions": [
                    ("can_view_message_by_manager", "Право менеджера на просмотр")
                ],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_view_newsletter_by_manager",
                        "can_view_newsletter_by_manager",
                    ),
                    (
                        "can_change_newsletter_by_manager",
                        "can_change_newsletter_by_manager",
                    ),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
