# Generated by Django 4.2.2 on 2025-02-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailmaster", "0024_alter_message_options_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("title",),
                "permissions": [
                    ("can_view_message_by_manager", "can_view_message_by_manager")
                ],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
