# Generated by Django 4.2.2 on 2024-10-24 13:55

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username_user_avatar_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.TextField(
                blank=True,
                help_text="Введите название компании",
                null=True,
                verbose_name="Название компании",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="страна"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="inn",
            field=models.CharField(
                blank=True,
                help_text="Введите индивидуальный номер налогоплательщика",
                max_length=12,
                null=True,
                verbose_name="ИНН",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="токен"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватарку",
                null=True,
                upload_to="users/avatars/",
                verbose_name="аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="номер телефона",
            ),
        ),
    ]
