# Generated by Django 4.2.2 on 2025-02-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_company_name_user_country_user_inn_user_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
